webpersonal/contact/urls.py
from django.urls.conf import path
from .views import ContactPageView

app_name = 'contact'

urlpatterns = [
    path('', ContactPageView.as_view(), name='home')
]

webpersonal/core/urls.py
from django.urls.conf import path
from .views import HomePageView
from django.views.generic import TemplateView

app_name='main'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('robots.txt', TemplateView.as_view(template_name='core/robots.txt', content_type='text/plain')),
]

webpersonal/portfolio/urls.py
from django.urls import path
from .views import PortfolioPageView

app_name= 'portfolio'
urlpatterns = [
    path('', PortfolioPageView.as_view(), name='home')
]

webpersonal/webpersonal/urls.py
from django.contrib import admin
from django.urls import path, include
from portfolio import views as portfolio_views
from contact import views as contact_views

from django.conf import settings

urlpatterns = [
    # Path Core
    path('', include('core.urls')),

    # Path Portfolio
    path('portfolio/', include('portfolio.urls')),

    # Path Contact
    path('contact/', include('contact.urls')),
    path('admin/', admin.site.urls), 
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webpersonal/contact/models.py
from django.db import models

# Create your models here.

webpersonal/portfolio/models.py
from django.db import models
from multiselectfield import MultiSelectField

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=200, verbose_name="Título")
    description = models.TextField(verbose_name="Descripción")
    image = models.ImageField(verbose_name = 'Imagen', upload_to="projects")

    language_choice = (
        ('.django','.django'),
        ('.py','.py'),
        ('.js','.js'),
        ('.html','.html'),
        ('.css','.css'),
    )
    language = MultiSelectField(choices = language_choice, verbose_name="Lenguajes")

    program_choice = (
        ('.vscode','.vscode'),
        ('.figma','.figma')
    )
    program = MultiSelectField(choices = program_choice, verbose_name = 'Programas')
    url_link =  models.URLField(null=True, blank=True, verbose_name="Dirección Web")
    created = models.DateTimeField(auto_now_add=True, verbose_name = 'Fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name = 'Fecha de actualización')

    class Meta:
        verbose_name = 'proyecto'
        verbose_name_plural = 'proyectos'
        ordering = ['-created']

    def __str__(self):
        return self.title

webpersonal/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label='Tell me your name', max_length=100)
    email = forms.EmailField(label='Enter your email')
    message = forms.CharField(label='Message', max_length=300)

webpersonal/contact/views.py
from django import forms
from .forms import ContactForm
from django.views.generic.edit import FormView
from django.core.mail import message, send_mail

class ContactPageView(FormView):
    template_name = 'contact/contact.html'
    form_class = ContactForm
    success_url = '/contact/' + '?ok'


    def get_form(self, form_class=None):
        form = super(ContactPageView, self).get_form()
        # Inputs
        form.fields['name'].widget = forms.TextInput(
            attrs={'class': 'form-control mb-2 mt-2', 'placeholder': 'Enter your name'})
        form.fields['email'].widget = forms.EmailInput(
            attrs={'class': 'form-control mb-2 mt-2', 'placeholder':'Enter your email'})
        form.fields['message'].widget = forms.Textarea(
            attrs={'class': 'form-control mb-4 mt-2', 'cols':'30', 'rows':'5', 'placeholder':'Your message here...'})
        return form


    def form_valid(self, form):
        name = form.cleaned_data.get('name')
        email = form.cleaned_data.get('email')
        message = form.cleaned_data.get('message')
        send_mail(name,message,email,['juanmarchantdev@gmail.com'],fail_silently=False)
        return super().form_valid(form)

webpersonal/core/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic.base import TemplateView

# Create your views here.

class HomePageView(TemplateView):
    template_name = 'core/home.html'

webpersonal/portfolio/views.py
from django.views.generic.base import TemplateView
from django.shortcuts import render
from .models import Project

# Create your views here.

class PortfolioPageView(TemplateView):
    template_name = 'portfolio/portfolio.html'

    def get_context_data(self):
        context = {
        'projects': Project.objects.all(),
        }
        return context
    

webpersonal/contact/templates/contact/contact.html
{% extends 'core/base.html' %}
{% block title %}Contact{% endblock title %}
{% block description_main %}If you have any questions about the source code of my projects or want to talk about anything else, please do so! I will respond as quickly as possible {% endblock description_main %}
{% block canonical %}contact{% endblock canonical %}

{% block title_og %}Contact{% endblock title_og %}
{% block description_og %}If you have any questions about the source code of my projects or want to talk about anything else, please do so! I will respond as quickly as possible {% endblock description_og %}
{% block title_tw %}Contact{% endblock title_tw %}
{% block description_tw %}If you have any questions about the source code of my projects or want to talk about anything else, please do so! I will respond as quickly as possible {% endblock description_tw %}
{% block content %}
{% load static %}
<style>label{color:#C7F6FF;}</style>
<div class="container d-flex min-vh-100 justify-content-center items-align-center">
    <div class="row align-items-center p-3">        
        <div class="col-lg-5 col-md-8 col bg-bluee border-15r shadow-me p-4 mx-auto">    
            {% if 'ok' in request.GET %}
                <p style="background-color: #90E0EF; color:#0077B6; padding: 8px; border:3px solid #0077B6; border-radius: 5px; text-align:center;font-weight:500;">
                    Your email is already sent! Thank you for contacting me, I will respond as quickly as possible.
                </p>
            {% endif %}
            <div class="text-center ">
                {% include 'core/navbar.html' %}
                <h1 class="text-lightblue">Contact</h1>
                <p class="text-mediumblue">If you have any questions about the source code of my projects or want to talk about anything else, please do so! I will respond as quickly as possible
            </div>
            <form  method='post'>{% csrf_token %}
                {{form.as_p}}
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">Send</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

webpersonal/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> {% block title %}{% endblock title %} - Juan Marchant | Developer</title>
    {% load static %}
    <meta name="description" content="{% block description_main%}{% endblock description_main%}">
    <meta name="keywords">
    <meta name="robots" content="index, follow">
    <link rel="canonical" href="http://juanmarchant.com/{% block canonical%}{% endblock canonical %}" />
    <!-- Meta tags Facebook-->
    <meta property="og:url" content="https://www.juanmarchant.com/">
    <meta property="og:type" content="website">
    <meta property="og:title" content=" {% block title_og %}{% endblock title_og %} - Juan Marchant | Developer">
    <meta property="og:description" content="{% block description_og%}{% endblock description_og%}">
    <meta property="og:image" content="{% static 'img/me.png'%}">
    <!-- Meta tags Twitter-->
    <meta name="twitter:card" content="summary_large_image">
    <meta property="twitter:domain" content="juanmarchant.com">
    <meta property="twitter:url" content="https://www.juanmarchant.com/">
    <meta name="twitter:title" content=" {% block title_tw %}{% endblock title_tw %} - Juan Marchant | Developer">
    <meta name="twitter:description" content="{% block description_tw%}{% endblock description_tw%}">
    <meta name="twitter:image" content="{% static 'img/me.png'%}">

    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'core/img/favicon/apple-icon-57x57.png'%}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'core/img/favicon/apple-icon-60x60.png'%}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'core/img/favicon/apple-icon-72x72.png'%}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'core/img/favicon/apple-icon-76x76.png'%}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'core/img/favicon/apple-icon-114x114.png'%}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'core/img/favicon/apple-icon-120x120.png'%}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'core/img/favicon/apple-icon-144x144.png'%}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'core/img/favicon/apple-icon-152x152.png'%}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'core/img/favicon/apple-icon-180x180.png'%}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'core/img/favicon/android-icon-192x192.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'core/img/favicon/favicon-32x32.png'%}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'core/img/favicon/favicon-96x96.png'%}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'core/img/favicon/favicon-16x16.png'%}">
    <meta name="theme-color" content="#ffffff">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'core/css/main.css' %}">
  </head>
  <body>
    {% block content %} {% block navbar %}{% endblock navbar %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

webpersonal/core/templates/core/home.html
{% extends 'core/base.html' %}
{% block title %}Home{% endblock title %}
{% block description_main %}I'm a chilean based, apassionate about web development and excited for knowing more about it.{% endblock description_main %}
{% block canonical %}{% endblock canonical %}

{% block title_og %}Home{% endblock title_og %}
{% block description_og %}I'm a chilean based, apassionate about web development and excited for knowing more about it.{% endblock description_og %}
{% block title_tw %}Home{% endblock title_tw %}
{% block description_tw %}I'm a chilean based, apassionate about web development and excited for knowing more about it.{% endblock description_tw %}

{%block content %} 
{% load static %}

<div class="container d-flex min-vh-100 justify-content-center align-items-center ">  
  <div class="row align-items-center row-cols-lg-2 row-cols-md-2 row-cols-sm-1 row-cols-1">
    <div class="col text-center pb-3">
      <img class="img-fluid me" src="{% static 'core/img/me.png' %}" alt="Ilustracion de Juan Marchant" />
    </div>
    <div class="col">
      {% include 'core/navbar.html' %}
      <header>
        <h1 class="text-lightblue">Hello I'm Juan Marchant</h1>
        <h2 class="text-mediumblue fw-500 pb-1 ">Django Web Developer</h2>
        <p class="text-lightblue">
          I'm a chilean based, apassionate about web development and excited for knowing more about it.
          I use daily: <code>.py</code>, <code>.js</code>, <code>.html</code> & <code>.css</code>
        </p>

        <p class="text-mediumblue ">
          At the moment I'm engaged to do more courses of diferent frameworks, programming language & trying to get a job 
          for more experience in the world of web developers.
          <br>
          This is my first online portolio. Fell free to explore & tell me what you think about it!
        </p>

        <div class="py-3 ">
          <a class="me-2" target="_blank" href="https://github.com/juanmarchant"><img src="{% static 'core/img/Github.png'%}" alt="Github"></a>
          <a class="mx-2" target="_blank" href="https://www.instagram.com/juanmarchant__/"><img src="{% static 'core/img/Instagram.png'%}" alt="Instagram"></a>
        </div>
      </header>
    </div>
  </div>
</div>

{% endblock content %}

webpersonal/core/templates/core/navbar.html
<nav>
  <ul class="list-inline">
    <li class="list-inline-item"><a class="text-lightblue text-decoration-none" href="{% url 'main:home' %}">Home</a></li>
    <li class="list-inline-item"><a class="text-lightblue text-decoration-none" href="{% url 'portfolio:home' %}">My projects</a></li>
    <li class="list-inline-item"><a class="text-lightblue text-decoration-none" href="{% url 'contact:home' %}">Contact</a></li>
  </ul>
</nav>

webpersonal/portfolio/templates/portfolio/portfolio.html
{% extends 'core/base.html' %} 
{% block title %}Portfolio{% endblock title %}
{% block description_main %}You can see all my projects and you can see their websites respectively{% endblock description_main %}
{% block canonical %}portfolio{% endblock canonical %}

{% block title_og %}Portfolio{% endblock title_og %}
{% block description_og %}You can see all my projects and you can see their websites respectively{% endblock description_og %}
{% block title_tw %}Portfolio{% endblock title_tw %}
{% block description_tw %}You can see all my projects and you can see their websites respectively{% endblock description_tw %}
{%block content %} 
{% load static %}

<div class="container-fluid p-5">
  {% include 'core/navbar.html' %}
  <div class="row row-cols-lg-4 row-cols-md-2 row-cols-sm-1 row-cols-1 g-5">
  {% for project in projects %}
    <div class="col">
      <div class="card h-100 bg-bluee border-15r shadow-me ">
        <img class="card-img-top border-top-15r" src="{{project.image.url}}" alt="{{project.title}}" />
        <div class="card-body">
          <h5 class="card-title text-mediumblue">{{project.title}}</h5>
          <p class="card-text text-lightblue">
            {{project.description}}
          </p>

          <p class="text-lightblue">Languages or Frameworks: <br>
          {% for language in project.language %}
            <code>{{language}}</code>
          {% endfor %}
          </p>
          <p class="text-lightblue">Programs for code or desing: <br> 
          {% for program in project.program %}
            <code>{{program}}</code>
          {% endfor %}
          </p>
          {% if project.url_link != NULL %}
            <a href="{{project.url_link}}" class="text-mediumblue text-decoration-none">Check Website ←</a>
          {% else %}
            <a href="#" class="btn-link disable text-mediumblue text-decoration-line-through">Check Website ←</a>
            <small class="text-white">(soon)</small>
          {% endif %}
        </div>
      </div>
    </div>
  {% endfor %}
  </div>
</div>
{% endblock content %}